### ISSUE TITLE
ConceptNet Vectors

### ISSUE THREAD

**Issue by waveboo** [gyhandy/Humanoid-Vision-Engine#3]
Hi @gyhandy , thanks for your great work!
I am wondering where to download the vector.npy in [here](https://github.com/gyhandy/Humanoid-Vision-Engine/blob/main/Zero_shot/zero_shot.py#L13), because i do not find the download link on the ConceptNet website.
Could you please provide a download link to the vector.npy or kindly suggest me where to find it? Thanks in advance.

**Comment by gyhandy** [comment]
https://github.com/commonsense/conceptnet-numberbatch

Thanks!
