### ISSUE TITLE
About entity segmentation

### ISSUE THREAD

**Issue by hellog2n** [gyhandy/Humanoid-Vision-Engine#9]
Hi,
I am preprocessing the datas. 
Could you provide me information about the entity segmentation model in your data preprocessing step? 

Did you use the official pretrained model provided by the entity segmentation official github site or train the segmentation model on your data directly?

**Comment by gyhandy** [comment]
Yes, we use the official pretrained model provided by the entity segmentation official GitHub site. Thanks!

**Comment by hellog2n** [comment]
Thank you for responding me! @gyhandy 
Also I am extracting foreground image from original image and I am curious whether the choice of entity segmentation model might influence the quality of the extracted foreground images. Does the quality of foreground image align solely with GradCAM's performance, as mentioned in the paper, or can it also be attributed to entity segmentation model types (like R50, Swin Transformer... etc)?

I would like to know which type of the entity segmentation model you used.

Thank you.
